# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

resources:
  repositories:
  - repository: templates
    type: github
    endpoint: jpfrezzarin
    name: jpfrezzarin/azure-pipeline-templates

pool:
  vmImage: 'ubuntu-18.04'

variables:
  nodeVersion: '12.x'
  ionicVersion: '5.4.16'
  cordovaVersion: '9.0.0'

stages:
  - stage: qa
    displayName: quality
    jobs:
      - job: unit_test_and_sonar
        displayName: unit test and sonarcloud
        steps:
        - template: ionic/ionic-unit-test-with-sonar.yml@templates
          parameters:
            nodeVersion: '$(nodeVersion)'
            sonarEndpoint: 'jpfrezzarin-sonarcloud'
            sonarOrganization: 'jpfrezzarin'
            sonarProjectKey: 'jpfrezzarin.ionic-calculator'
            sonarProjectName: 'Ionic Calculator'

  - stage: build_android
    displayName: build and publish - android
    dependsOn: qa
    jobs:
      - job: build_android_dev
        displayName: build and publish android dev
        steps:
        - template: ionic/ionic-build-publish-android.yml@templates
          parameters:
            nodeVersion: '$(nodeVersion)'
            ionicVersion: '$(ionicVersion)'
            cordovaVersion: '$(cordovaVersion)'
            artifactName: 'android-dev'

      - job: build_android_prd
        displayName:  build and publish android prd
        dependsOn: build_android_dev
        steps:
        - template: ionic/ionic-build-publish-android.yml@templates
          parameters:
            nodeVersion: '$(nodeVersion)'
            ionicVersion: '$(ionicVersion)'
            cordovaVersion: '$(cordovaVersion)'
            buildConfiguration: 'release'
            artifactName: 'android-prd'
