# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'ubuntu-18.04'

variables:
  nodeVersion: '12.x'
  angularVersion: '9.1.2'

steps:

- task: NodeTool@0
  displayName: use node $(nodeVersion)
  inputs:
    versionSpec: '$(nodeVersion)'

- task: Npm@1
  displayName: npm install
  inputs:
    command: 'install'

- task: Npm@1
  inputs:
    command: 'custom'
    customCommand: 'install angular@$(angularVersion)'
    
- task: CmdLine@2
  inputs:
    script: 'ng test --watch=false --code-coverage --browsers=ChromeHeadless'
